---
- hosts: all
  become: yes
  vars:
    - ldap_host_admin_user: "{{ lookup('env','USER') }}"
  vars_prompt:
    - name: "ldap_host_admin_user_passwd"
      prompt: "Please enter your LDAP password"
      private: yes
  roles:
    - common
    - ldap_host
