---
# tasks file for ldap_client

- name: (ldap_client) Vars files are included
  include_vars: "{{ item }}"
  with_items:
  - "{{ ansible_distribution }}.yml"
  - "{{ ansible_local.osc_facts.env }}.yml"

- name: (ldap_client) Required packages are installed and updated
  dnf:
    name: "{{ item }}"
  with_items: "{{ ldap_client_packages }}"

- name: (ldap_client) Templates are deployed
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ ldap_client_files }}"
  notify:
    - (handler) Restart sssd
    - (handler) Restart oddjobd

