ldap_host_files:
    - src: 'sssd.conf.j2'
      dest: '/etc/sssd/sssd.conf'
      owner: 'root'
      group: 'root'
      mode: 600
    - src: 'ldap.conf.j2'
      dest: '/etc/ldap/ldap.conf'
      owner: 'root'
      group: 'root'
      mode: 644

ldap_host_packages:
    - sssd
    - oddjob-mkhomedir
    - ldap-utils
    - libpam-sss
    - libnss-sss
    - libnss-ldap

ldap_host_ldap_directory:
  path: '/etc/ldap'
  owner: 'root'
  group: 'root'
