---
# handlers file for ldap_host

- name: (ldap_host) Restart sssd
  service:
    name: sssd
    state: restarted
    enabled: yes

- name: (ldap_host) Restart oddjobd
  service:
    name: oddjobd
    state: restarted
    enabled: yes
