---
# tasks file for lxc_container

- name: LXC container is created
  lxc_container:
    name: "{{ lxc_container_name }}"
    state: started
    template: "fedora"
    lxc_patch: "/var/lib/libvirt/filesystems/{{ lxc_container_name }}"
  register: lxc_container_started

- name: Wait for the network to be setup in the containers
  wait_for_connection:


